services:
  - type: web
    name: spartan4-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1